---
- name: Setup LAMP stack on servers
  hosts: all
  become: yes
  tasks:
    # Update the apt repository and upgrade the system
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist

    # Install Apache
    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    # Install PHP and necessary modules
    - name: Install PHP and modules
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
          - php-cli
          - php-xml
          - php-curl
        state: present

    # Install MySQL Server (on database servers only)
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    # Ensure Apache is running and enabled to start at boot
    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    # Ensure MySQL is running and enabled to start at boot (on database servers only)
    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: yes


  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
